name: Build

on:
  push:

jobs:
  Ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: |
          mkdir DavilexConverter/build && cd DavilexConverter/build
          cmake -DCMAKE_BUILD_TYPE=Release ..
          cmake --build .
          strip --strip-unneeded DavilexConverter
          cp -r ../../LICENSE ../../README.md ./
      - name: Publish artifacts
        uses: actions/upload-artifact@v4
        with:
          name: DavilexConverter-linux
          path: |
            DavilexConverter/build/DavilexConverter
            DavilexConverter/build/LICENSE
            DavilexConverter/build/README.md

  Windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v2
      - name: Build
        run: |
          cd DavilexConverter/
          msbuild DavilexConverter.sln -t:rebuild -verbosity:diag -property:Configuration=Release
          cp x64/Release/DavilexConverter.exe ../
      - name: Publish artifacts
        uses: actions/upload-artifact@v4
        with:
          name: DavilexConverter-msbuild
          path: |
            DavilexConverter.exe
            LICENSE
            README.md

  Release:
    needs: [Ubuntu, Windows]
    if: ${{ github.ref_type == 'tag' }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        build: [linux, windows]
    steps:
    - uses: actions/download-artifact@v4
    - name: Zip artifacts
      run: |
        zip -r DavilexConverter-${{matrix.build}}.zip DavilexConverter-${{matrix.build}}
    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        files: DavilexConverter-${{matrix.build}}.zip
        prerelease: true
        name: DavilexConverter ${{ github.ref_name }}
        tag_name: ${{ github.ref_name }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}