name: Build

on:
  push:

jobs:
  Ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: |
          mkdir DavilexConverter/build && cd DavilexConverter/build
          cmake -DCMAKE_BUILD_TYPE=Release ..
          cmake --build .
          strip --strip-unneeded DavilexConverter
          cp -r DavilexConverter ../../
      - name: Publish artifacts
        uses: actions/upload-artifact@v4
        with:
          name: DavilexConverter-linux
          path: |
            DavilexConverter
            LICENSE
            README.md

  Windows:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - name: Install dependencies
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          install: >-
            mingw-w64-x86_64-gcc
            mingw-w64-x86_64-binutils
            mingw-w64-x86_64-make
            mingw-w64-x86_64-cmake
          update: true
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: |
          mkdir DavilexConverter/build && cd DavilexConverter/build
          cmake -DCMAKE_BUILD_TYPE=Release ..
          cmake --build .
          strip --strip-unneeded DavilexConverter.exe
          cp -r DavilexConverter.exe ../../
      - name: Publish artifacts
        uses: actions/upload-artifact@v4
        with:
          name: DavilexConverter-windows
          path: |
            DavilexConverter.exe
            LICENSE
            README.md

  Release:
    needs: [Ubuntu, Windows]
    if: ${{ github.ref_type == 'tag' }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        build: [linux, windows]
    steps:
    - uses: actions/download-artifact@v4
    - name: Zip artifacts
      run: |
        zip -r DavilexConverter-${{matrix.build}}.zip DavilexConverter-${{matrix.build}}
    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        files: DavilexConverter-${{matrix.build}}.zip
        prerelease: true
        name: DavilexConverter ${{ github.ref_name }}
        tag_name: ${{ github.ref_name }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}